<?php
echo $this->doctype();
?>
<html>
    <head>
        <META HTTP-EQUIV="Pragma" CONTENT="no-cache">
        <META HTTP-EQUIV="Expires" CONTENT="-1">
        <?php
        echo $this->headMeta();
        ?>
        <?php
        $this->headTitle($this->title);
        echo $this->headTitle();
        echo $this->headLink()->appendStylesheet($this->baseUrl('/css/login.css'));
        echo $this->jQuery();
        ?>
    </head>
    <h1><?= $this->escape($this->title); ?></h1>
    <form method='post' action='<?= $this->escape($this->action); ?>'>
        <table>
            <tr>
                <td><?= $this->escape($this->username); ?></td>
                <td><input type='text' name='username'></td>
            </tr>
            <tr>
                <td><?= $this->escape($this->password); ?></td>
                <td><input type='password' name='password'></td>
            </tr>
        </table>
        <input type='submit' name='login' value='Login'>
    </form>
</body>
</html>