<?php
echo $this->doctype();
?>
<html>
    <head>
        <META HTTP-EQUIV="Pragma" CONTENT="no-cache">
        <META HTTP-EQUIV="Expires" CONTENT="-1">
        <?php
            echo $this->headMeta();
        ?>
        <?php
            $this->title = "Pievienot jaunu tēmu";
            $this->headTitle($this->title);
            echo $this->headTitle();
            echo $this->headLink()->appendStylesheet($this->baseUrl('/css/style.css'));
            echo $this->headLink()->appendStylesheet($this->baseUrl('/css/entryForm.css'));
            echo $this->jQuery();
        ?>
    </head>
    <body>
        <?php            
            echo $this->form ;
        ?>
    </body>
</html>