<?php
echo $this->doctype();
?>
<html>
    <head>
        <META HTTP-EQUIV="Pragma" CONTENT="no-cache">
        <META HTTP-EQUIV="Expires" CONTENT="-1">
        <?php
            echo $this->headMeta();
        ?>
        <?php
            echo $this->headTitle();
            echo $this->headLink()->appendStylesheet($this->baseUrl('/css/style.css'));
            echo $this->jQuery();
        ?>
    </head>
    <body>
        <div id="sectionContentContainer" class="section topicSection">
            <h1>Datorikas fakultātes Studentu pašpārvaldes Akadēmiskā komisija</h1>
            <?
                $v1 = $_GET['section'];
                $v2 = $_GET['undersection'];
                $v3 = $_GET['underundersection'];
                echo "Variable One Value: $v1
                Variable Two Value: $v2
                Variable Three Value: $v3";
            ?>
        </div>
    </body>
</html>