<?php
echo $this->doctype();
?>
<html>
    <head>
        <META HTTP-EQUIV="Pragma" CONTENT="no-cache">
        <META HTTP-EQUIV="Expires" CONTENT="-1">
        <?php
            echo $this->headMeta();
        ?>
        <?php
            echo $this->headTitle();
            echo $this->headLink()->appendStylesheet($this->baseUrl('/css/style.css'));
            echo $this->jQuery();
        ?>
    </head>
    <body>
        
        <div class="section">
           <?php foreach($this->sections as $sections) : ?>
               
               <!-- Generates names of sections -->
               <?php
                    $section_name = $this->escape($sections->section_name);
                    $section_id = $this->escape($sections->section_id);
                    
                    echo "<h1><a href='/index/section?section_id=".$section_id."' > ".$section_name."</a></h1>";
                    
               ?>
               
               <div id="sectionContentContainer" class="section topicSection">
                    <!-- Displays names of undersections -->
                    <?php foreach($this->undersections as $undersections) :
                        // Retrieves the section_id under which the undersections lie
                        $undersectionSectionId = $this->escape($undersections->section_id);

                        // If the undersection's section_id is equal to the current section's id
                        if ($section_id == $undersectionSectionId)
                        {
                            $undersection_name = $this->escape($undersections->undersection_name);
                            $undersection_id = $this->escape($undersections->undersection_id);

                            // Displays the corresponding undersections, which belong to the current section
                            echo "<h2><a href='/index/undersection?undersection_id=".$undersection_id."' >".$undersection_name."</a></h2>";
                        }                  
                    endforeach; ?>
                </div>
               
           <?php endforeach; ?>
        </div>
        
    </body>
</html>