<?php
echo $this->doctype();
?>
<html>
    <head>
        <META HTTP-EQUIV="Pragma" CONTENT="no-cache">
        <META HTTP-EQUIV="Expires" CONTENT="-1">
        <?php
            echo $this->headMeta();
        ?>
        <?php
            echo $this->headTitle();
            echo $this->headLink()->appendStylesheet($this->baseUrl('/css/style.css'));
            echo $this->jQuery();
        ?>
    </head>
    <body>
        
        <?php
            $v1 = $_GET['section_id'];

            $sectionName = "No section name found";

            foreach ($this->sections as $sections) :                              // Šis izmet error par $sections
                $section_id = $this->escape($sections->section_id);
                if ($section_id == $v1) {
                    $sectionName = $this->escape($sections->section_name);
                    break;
                }
            endforeach;
        ?>
        
        <div id="sectionContentContainer" class="section topicSection">
            <h1><?php echo $sectionName ?></h1>
        </div>
    </body>
</html>