<?php
echo $this->doctype();
?>
<html>
    <head>
        <META HTTP-EQUIV="Pragma" CONTENT="no-cache">
        <META HTTP-EQUIV="Expires" CONTENT="-1">
        <?php
            echo $this->headMeta();
        ?>
        <?php
            echo $this->headTitle();
            echo $this->headLink()->appendStylesheet($this->baseUrl('/css/style.css'));
            echo $this->headLink()->appendStylesheet($this->baseUrl('/css/topicView.css'));
            echo $this->headLink()->appendStylesheet($this->baseUrl('/css/replyView.css'));
            echo $this->jQuery();
        ?>
    </head>
    <body>
        
        <?php
            // Retrieving the parameter added in the link
            $v1 = $_GET['topic_id'];

            $topicId = 0;
            
            // Cycle goes through the entry table
            foreach ($this->entries as $entries) :
                $entry_id = $this->escape($entries->entry_id);
                // If the current row entry_id equals the number in the link..
                if ($entry_id == $v1) {
                    // The current section_name is saved in the $sectionName variable
                    $topicId = $this->escape($entries->entry_id);
                    $topicName = $this->escape($entries->entry_topic);
                    $topicText = $this->escape($entries->entry_text);
                    $topicAuthor = $this->escape($entries->user_id);
                    break;
                }
            endforeach;
        ?>
        
        <div class="buttonContainer">
            <div class="button">
                <?php
                echo "<a href='/index/addtopic'>Izveidot jaunu tēmu</a>";
                ?>
            </div>
            <div class="button replyButton">
                <?php
                echo "<a href='/post/addreply?topic_id=" . $topicId . "'>Pievienot atbildi</a>";
                ?>
            </div>
        </div>
    
        <div class="firstPost section">
            <h1><?= $topicName ?></h1>
            <p id="authorBox">Author: <?= $topicAuthor ?></p> 
            <p id="textSection"><?= $topicText ?></p>
        </div>
        <div id="replyContainer">
            
            <!-- Displays replies -->
            <?php foreach($this->replies as $replies) :
                // Retrieves the section_id under which the undersections lie
                $replyTopicId = $this->escape($replies->topic_id);
                
                // If the undersection's section_id is equal to the current section's id
                if ($replyTopicId == $topicId)
                {
                    $replyAuthor = $this->escape($replies->user_id);
                    $replyText = $this->escape($replies->reply_text);
                    $replyTime = $this->escape($replies->reply_time);
                    
                    // Displays the corresponding undersections, which belong to the current section
                    
                    echo "<div class='replyBox'>";
                        echo "<div class='replyInfo'>";
                            echo "<div class='replyAuthor'><p>Autors: ".$replyAuthor."</p></div>";
                            echo "<div class='replyTime'><p>Atbildes laiks: ".$replyTime."</p></div>";
                        echo "</div>";
                        echo "<div class='replyTextBox'>";
                            echo "<p>".$replyText."</p>";
                        echo "</div>";
                    echo "</div>";
                }                  
            endforeach; ?>

        </div>
    </body>
</html>